### ISSUE TITLE
WIP: Upcoming features and improvements

### ISSUE THREAD

**Issue by julianfssen** [julianfssen/tweetkit#1]
Hi! Thanks for using this gem.

`tweetkit` is a Twitter v2 API wrapper inspired by the `octokit` gem and the current `twitter` gem. That said, `tweetkit` is currently very rudimentary and is nowhere near polished enough for reliable production usage.

With that in mind, I'm working on new features and improvements to make `tweetkit` suitable for serious usage, as shown below:

### Flexible search DSL
The search DSL is already available in `tweetkit`. It is, however, quite basic and lacks documentation. In short, the search DSL allows you to easily create search statements based on Twitter's [search operators](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#list).

Here's an example search code:

```ruby
  client.search 'lionel messi' do
    contains 'psg', 'barcelona'
    without 'manchester united', 'manchester city'
    is_a :retweet
    is_not :verified
    has :media
  end
```

This searches for retweets containing the phrase `lionel messi` that also contains the words `psg` _and_ `barcelona`. The matched retweets should not have any occurrences of `manchester united` and `manchester city`. The retweets should not be from verified accounts and it should contain a media object, such as a photo, GIF, or video, as determined by Twitter.

There is a lot to improve for this search DSL and I'm hoping to make it as easy-to-use and flexible as similar DSLs like `RSpec`, `builder`, and so on.

### All v2 endpoints

The gem currently only supports fetching and searching for tweets. The plan is to cover all `v2` endpoints, both existing and upcoming. I do not plan to add `v1` endpoints at the moment as it is covered completely by the current `twitter` gem. It will be also be replaced by the `v2` endpoints soon so they'll not be worked on unless there's demand from the community.

### Custom error handling
Create a custom error class to handle errors from the Twitter API. Currently, errors are handled by Ruby while some are returned as JSON responses from Twitter. This works OK-ish but ideally, I want to create a custom error class to improve error handling and improve debugging while using the gem.

### Improved response object
Currently, the wrapper returns a custom `Tweetkit::Response` object. This response object contains a `Tweets` class, which is a collection of `Tweet` objects that contain the tweet content and `id`. Depending on the fields and expansions you included when calling the endpoints, you may also have access to a `Resources` and/or `Meta` class which contains tweet metadata, fields and expansions [(read more on Twitter fields and expansions in the v2 endpoints)](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/using-fields-and-expansions).

The plan is to improve the response both usage and implementation-wise, so it'll be easy to work with it and also understand the code if needed.

### Pagination
Currently, results are returned as is from Twitter's API, with pagination handled by passing in options when calling. This can be improved by introducing pagination to every (necessary) endpoint without the need for a `page` option. Instead, you can call `response.next` instead to get the next page or `response.prev` to go back.

### Better client connection structure
Currently, the gem is relying on the internal `Faraday` module to fetch results with a simple `get` call. This may not work well for repeated calls in a short span of time or if concurrency is needed. I'm looking to make the connection module customizable so it can be tweaked for your desired HTTP library and specific use cases.

### Documentation and tests

There is currently no documentation and tests for the gem. This will be added along the way as I work on the features and improvements.

These are the current tasks that are in my roadmap for this gem. Feel free to create issues or even submit PRs if you're interested. Thanks again for using this gem! :)

**Comment by julianfssen** [comment]
### Tasks in progress

**Flexible search DSL**

- [x] Add support for fields and expansions
- [x] Add support for search operators
- [ ] Add support for search operator order of operations
- [ ] Add support for filtered streams and academic research

**Add all `v2` Endpoints**

- [ ] Tweets endpoints
- [ ] Users endpoints
- [ ] Spaces endpoints
- [ ] Compliance endpoints

**Improved response object**

- [x] Add support for `Tweets`, `Fields`, and `Expansions` objects
- [x] Add helper methods to extract expansions and metadata from tweets

**Pagination**

- [x] Add pagination support for `next_token`, `previous_token`, and `pagination_token`
- [x] Add pagination support the for `search` endpoint

**Improved client connection**

- [ ] Better connection reuse logic
- [ ] Improved support for multithread / concurrent client connections

**Error handling**

- [ ] Add custom error class
- [ ] Add error handling for all HTTP status codes and Twitter response codes
- [ ] Add error handling for syntax / usage errors

**Documentation**

- [ ] Add documentation and example usage for all endpoints
- [ ] Add documentation for all modules and classes

**Tests**

- [ ] Add tests for all endpoints
- [ ] Add tests for object creation, request creation, and important business logic
